DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS items CASCADE;


CREATE TABLE IF NOT EXISTS users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name  VARCHAR(255)                            NOT NULL,
    user_email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (user_email)
);

CREATE TABLE IF NOT EXISTS requests
(
    request_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    request_description VARCHAR(255)                            NOT NULL,
    requestor_id        BIGINT                                  NOT NULL,
    request_created     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_name        VARCHAR(255)                            NOT NULL,
    item_description VARCHAR(512)                            NOT NULL,
    available        BOOLEAN,
    owner_id         BIGINT REFERENCES users (user_id),
    request_id       BIGINT REFERENCES requests (request_id),
    CONSTRAINT pk_item PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date     TIMESTAMP WITHOUT TIME ZONE,
    end_date       TIMESTAMP WITHOUT TIME ZONE,
    item_id        BIGINT REFERENCES items (item_id),
    booker_id      BIGINT REFERENCES users (user_id),
    booking_status VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);


CREATE TABLE IF NOT EXISTS comments
(
    comment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_text    VARCHAR(512)                            NOT NULL,
    item_id         BIGINT REFERENCES items (item_id),
    author_id       BIGINT REFERENCES users (user_id),
    comment_created TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (comment_id)
);

